package org.openmrs.module.patientmatching;

/**
 * A class to represent reports generated by the patientmatching module.
 * Initially, reports were stored as xml files in the users machine.
 * 
 * However, reports are being moved into the database as part of plans
 * to move all external flat files into a database.
 */
import java.util.ArrayList;
import java.util.List;

public class Report {
	private Long reportId;
	private String reportName;
	private List<MatchingSet> matchingSetList;
	
	public Long getReportId() {
		return reportId;
	}
	public void setReportId(Long reportId) {
		this.reportId = reportId;
	}
	public String getReportName() {
		return reportName;
	}
	public void setReportName(String reportName) {
		this.reportName = reportName;
	}
	public List<MatchingSet> getMatchingSetList() {
		return matchingSetList;
	}
	public void setMatchingSetList(List<MatchingSet> matchingSet) {	
		this.matchingSetList = matchingSet;
	}
}
