package org.openmrs.module.patientmatching;

/**
 * A class to represent reports generated by the patientmatching module.
 * Initially, reports were stored as xml files in the users machine.
 * 
 * However, reports are being moved into the database as part of plans
 * to move all external flat files into a database.
 */

import org.openmrs.User;

import java.util.Date;
import java.util.List;
import java.util.Set;

public class Report {
	private Long reportId;
	private String reportName;
    private User createdBy;
    private Date createdOn;
	private List<MatchingSet> matchingSetList;
    private Set<PatientMatchingConfiguration> usedConfigurationList;
	
	public Long getReportId() {
		return reportId;
	}
	public void setReportId(Long reportId) {
		this.reportId = reportId;
	}
	public String getReportName() {
		return reportName;
	}
	public void setReportName(String reportName) {
		this.reportName = reportName;
	}
	public List<MatchingSet> getMatchingSetList() {
		return matchingSetList;
	}
	public void setMatchingSetList(List<MatchingSet> matchingSet) {	
		this.matchingSetList = matchingSet;
	}

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public Set<PatientMatchingConfiguration> getUsedConfigurationList() {
        return usedConfigurationList;
    }

    public void setUsedConfigurationList(Set<PatientMatchingConfiguration> usedConfigurationList) {
        this.usedConfigurationList = usedConfigurationList;
    }
}
